-- begin MYPROJECT_PRODUCER
alter table MYPROJECT_PRODUCER add constraint FK_MYPROJECT_PRODUCER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create unique index IDX_MYPROJECT_PRODUCER_UK_NAME on MYPROJECT_PRODUCER (NAME) where DELETE_TS is null ^
create index IDX_MYPROJECT_PRODUCER_ON_USER on MYPROJECT_PRODUCER (USER_ID)^
-- end MYPROJECT_PRODUCER
-- begin MYPROJECT_PRODUCT
alter table MYPROJECT_PRODUCT add constraint FK_MYPROJECT_PRODUCT_ON_PRODUCER foreign key (PRODUCER_ID) references MYPROJECT_PRODUCER(ID)^
create unique index IDX_MYPROJECT_PRODUCT_UK_NAME on MYPROJECT_PRODUCT (NAME) where DELETE_TS is null ^
create index IDX_MYPROJECT_PRODUCT_ON_PRODUCER on MYPROJECT_PRODUCT (PRODUCER_ID)^
-- end MYPROJECT_PRODUCT
-- begin MYPROJECT_STORE
alter table MYPROJECT_STORE add constraint FK_MYPROJECT_STORE_ON_RETAILER foreign key (RETAILER_ID) references MYPROJECT_RETAILER(ID)^
create unique index IDX_MYPROJECT_STORE_UK_NUM on MYPROJECT_STORE (NUM) where DELETE_TS is null ^
create index IDX_MYPROJECT_STORE_ON_RETAILER on MYPROJECT_STORE (RETAILER_ID)^
-- end MYPROJECT_STORE
-- begin MYPROJECT_RETAILER
create unique index IDX_MYPROJECT_RETAILER_UK_NAME on MYPROJECT_RETAILER (NAME) where DELETE_TS is null ^
-- end MYPROJECT_RETAILER
-- begin MYPROJECT_ORDER_PRODUCT
alter table MYPROJECT_ORDER_PRODUCT add constraint FK_MYPROJECT_ORDER_PRODUCT_ON_PRODUCT foreign key (PRODUCT_ID) references MYPROJECT_PRODUCT(ID)^
alter table MYPROJECT_ORDER_PRODUCT add constraint FK_MYPROJECT_ORDER_PRODUCT_ON_ORDER foreign key (ORDER_ID) references MYPROJECT_ORDER(ID)^
create index IDX_MYPROJECT_ORDER_PRODUCT_ON_PRODUCT on MYPROJECT_ORDER_PRODUCT (PRODUCT_ID)^
create index IDX_MYPROJECT_ORDER_PRODUCT_ON_ORDER on MYPROJECT_ORDER_PRODUCT (ORDER_ID)^
-- end MYPROJECT_ORDER_PRODUCT
-- begin MYPROJECT_ORDER
alter table MYPROJECT_ORDER add constraint FK_MYPROJECT_ORDER_ON_STORE foreign key (STORE_ID) references MYPROJECT_STORE(ID)^
create index IDX_MYPROJECT_ORDER_ON_STORE on MYPROJECT_ORDER (STORE_ID)^
-- end MYPROJECT_ORDER
-- begin MYPROJECT_STORE_PRODUCT
alter table MYPROJECT_STORE_PRODUCT add constraint FK_MYPROJECT_STORE_PRODUCT_ON_PRODUCT foreign key (PRODUCT_ID) references MYPROJECT_PRODUCT(ID)^
alter table MYPROJECT_STORE_PRODUCT add constraint FK_MYPROJECT_STORE_PRODUCT_ON_STORE foreign key (STORE_ID) references MYPROJECT_STORE(ID)^
create index IDX_MYPROJECT_STORE_PRODUCT_ON_PRODUCT on MYPROJECT_STORE_PRODUCT (PRODUCT_ID)^
create index IDX_MYPROJECT_STORE_PRODUCT_ON_STORE on MYPROJECT_STORE_PRODUCT (STORE_ID)^
-- end MYPROJECT_STORE_PRODUCT
-- begin MYPROJECT_PRICE_HISTORY
alter table MYPROJECT_PRICE_HISTORY add constraint FK_MYPROJECT_PRICE_HISTORY_ON_PRODUCT foreign key (PRODUCT_ID) references MYPROJECT_PRODUCT(ID)^
alter table MYPROJECT_PRICE_HISTORY add constraint FK_MYPROJECT_PRICE_HISTORY_ON_STORE foreign key (STORE_ID) references MYPROJECT_STORE(ID)^
create index IDX_MYPROJECT_PRICE_HISTORY_ON_PRODUCT on MYPROJECT_PRICE_HISTORY (PRODUCT_ID)^
create index IDX_MYPROJECT_PRICE_HISTORY_ON_STORE on MYPROJECT_PRICE_HISTORY (STORE_ID)^
-- end MYPROJECT_PRICE_HISTORY
