-- begin MYPROJECT_PRODUCER
alter table MYPROJECT_PRODUCER add constraint FK_MYPROJECT_PRODUCER_ON_PRODUCER_USER foreign key (PRODUCER_USER_ID) references SEC_USER(ID)^
create unique index IDX_MYPROJECT_PRODUCER_UK_PRODUCER_NAME on MYPROJECT_PRODUCER (PRODUCER_NAME) where DELETE_TS is null ^
create index IDX_MYPROJECT_PRODUCER_ON_PRODUCER_USER on MYPROJECT_PRODUCER (PRODUCER_USER_ID)^
-- end MYPROJECT_PRODUCER
-- begin MYPROJECT_PRODUCT
alter table MYPROJECT_PRODUCT add constraint FK_MYPROJECT_PRODUCT_ON_PRODUCT_PRODUCER foreign key (PRODUCT_PRODUCER_ID) references MYPROJECT_PRODUCER(ID)^
create unique index IDX_MYPROJECT_PRODUCT_UK_PRODUCT_NAME on MYPROJECT_PRODUCT (PRODUCT_NAME) where DELETE_TS is null ^
create index IDX_MYPROJECT_PRODUCT_ON_PRODUCT_PRODUCER on MYPROJECT_PRODUCT (PRODUCT_PRODUCER_ID)^
-- end MYPROJECT_PRODUCT
-- begin MYPROJECT_STORE
alter table MYPROJECT_STORE add constraint FK_MYPROJECT_STORE_ON_STORE_RETAILER foreign key (STORE_RETAILER_ID) references MYPROJECT_RETAILER(ID)^
create unique index IDX_MYPROJECT_STORE_UK_STORE_NUM on MYPROJECT_STORE (STORE_NUM) where DELETE_TS is null ^
create index IDX_MYPROJECT_STORE_ON_STORE_RETAILER on MYPROJECT_STORE (STORE_RETAILER_ID)^
-- end MYPROJECT_STORE
-- begin MYPROJECT_RETAILER
create unique index IDX_MYPROJECT_RETAILER_UK_RETAILER_NAME on MYPROJECT_RETAILER (RETAILER_NAME) where DELETE_TS is null ^
-- end MYPROJECT_RETAILER
