alter table MYPROJECT_STORE add constraint FK_MYPROJECT_STORE_ON_RETAILER foreign key (RETAILER_ID) references MYPROJECT_RETAILER(ID);
create unique index IDX_MYPROJECT_STORE_UK_NUM on MYPROJECT_STORE (NUM) where DELETE_TS is null ;
create index IDX_MYPROJECT_STORE_ON_RETAILER on MYPROJECT_STORE (RETAILER_ID);
