alter table MYPROJECT_PRODUCER add constraint FK_MYPROJECT_PRODUCER_ON_PRODUCER_USER foreign key (PRODUCER_USER_ID) references SEC_USER(ID);
create unique index IDX_MYPROJECT_PRODUCER_UK_PRODUCER_NAME on MYPROJECT_PRODUCER (PRODUCER_NAME) where DELETE_TS is null ;
create index IDX_MYPROJECT_PRODUCER_ON_PRODUCER_USER on MYPROJECT_PRODUCER (PRODUCER_USER_ID);
