alter table MYPROJECT_PRODUCT add constraint FK_MYPROJECT_PRODUCT_ON_PRODUCT_PRODUCER foreign key (PRODUCT_PRODUCER_ID) references MYPROJECT_PRODUCER(ID);
create unique index IDX_MYPROJECT_PRODUCT_UK_PRODUCT_NAME on MYPROJECT_PRODUCT (PRODUCT_NAME) where DELETE_TS is null ;
create index IDX_MYPROJECT_PRODUCT_ON_PRODUCT_PRODUCER on MYPROJECT_PRODUCT (PRODUCT_PRODUCER_ID);
