alter table MYPROJECT_STORE_PRODUCT add constraint FK_MYPROJECT_STORE_PRODUCT_ON_PRODUCT foreign key (PRODUCT_ID) references MYPROJECT_PRODUCT(ID);
alter table MYPROJECT_STORE_PRODUCT add constraint FK_MYPROJECT_STORE_PRODUCT_ON_STORE foreign key (STORE_ID) references MYPROJECT_STORE(ID);
create index IDX_MYPROJECT_STORE_PRODUCT_ON_PRODUCT on MYPROJECT_STORE_PRODUCT (PRODUCT_ID);
create index IDX_MYPROJECT_STORE_PRODUCT_ON_STORE on MYPROJECT_STORE_PRODUCT (STORE_ID);
