alter table MYPROJECT_PRODUCER add constraint FK_MYPROJECT_PRODUCER_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create unique index IDX_MYPROJECT_PRODUCER_UK_NAME on MYPROJECT_PRODUCER (NAME) where DELETE_TS is null ;
create index IDX_MYPROJECT_PRODUCER_ON_USER on MYPROJECT_PRODUCER (USER_ID);
