alter table MYPROJECT_PURCHASE add constraint FK_MYPROJECT_PURCHASE_ON_STORE foreign key (STORE_ID) references MYPROJECT_STORE(ID);
create index IDX_MYPROJECT_PURCHASE_ON_STORE on MYPROJECT_PURCHASE (STORE_ID);
